name: Release IPv7 Core (Phase 11)

on:
  push:
    tags:
      - 'v*' # Desencadena sobre push de tags como v1.0.0, v2.4

jobs:
  build-and-release:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: ipv7-core-linux-amd64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: ipv7-core-windows-amd64.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: ipv7-core-macos-amd64
            
    steps:
      - name: Checkout Código Fuente de The Great Sandbox
        uses: actions/checkout@v4

      - name: Instalar Rust Toolchain y Targets Multiplataforma
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Compilación Cruzada (Rust Build Release Extreme Optimization)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --manifest-path ipv7-core/Cargo.toml --target ${{ matrix.target }}

      - name: Formatear Nombre del Binario para Despliegue
        run: |
          mkdir out
          cp target/${{ matrix.target }}/release/ipv7-core* out/${{ matrix.artifact_name }} || cp ipv7-core/target/${{ matrix.target }}/release/ipv7-core* out/${{ matrix.artifact_name }}
        shell: bash

      - name: Subir Artifactos de IPv7 a GitHub Releases
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: out/${{ matrix.artifact_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
